### ISSUE TITLE
Methods name on `Channel`

### ISSUE THREAD

**Issue by He-Pin** [lampepfl/gears#28]
Hi nice projects, I was expect the name to be `send` & `recv/receive` but were `send` & `read`.

I was using https://docs.rs/tokio/latest/tokio/sync/mpsc/fn.channel.html and I think the `send` & `receive` better.

**Comment by natsukagami** [comment]
Hey! Naming is a hard problem :) we were looking for words that have equal lengths, hence `read` and `send`. `recv` was on the table but it doesn't read nicely off of the tongue.

**Comment by He-Pin** [comment]
That's true:)
