### ISSUE TITLE
Publish scala-native snapshot to maven center

### ISSUE THREAD

**Issue by He-Pin** [lampepfl/gears#34]
![image](https://github.com/lampepfl/gears/assets/501740/61b56f77-e806-47b6-aedd-2e7186725391)
I got errors when resolving the dependencies.

```
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-native/sbt-scala-native/scala_2.12/sbt_1.0/0.5.0-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/org.scala-native/sbt-scala-native/scala_2.12/sbt_1.0/0.5.0-SNAPSHOT/ivys/ivy.xml
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
```

**Comment by natsukagami** [comment]
Yes, unfortunately scala native 0.5 is not yet out, so the current way to set it up for gears is to locally publish it. I wrote some guides in CONTRIBUTING.md; but the tl;dr is if you're on Unix a `git submodule update` followed by `dependencies/publish-deps.sh` should prepare all the dependencies for you.

**Comment by armanbilge** [comment]
Scala Native 0.5.0 snapshots are available if you configure the snapshot resolver.

https://oss.sonatype.org/content/repositories/snapshots/org/scala-native/nativelib_native0.5.0-SNAPSHOT_3/

**Comment by He-Pin** [comment]
```
[error] (rootNative / update) sbt.librarymanagement.ResolveException: Error downloading org.scalameta:munit_native0.5.0-SNAPSHOT_3:1.0.0-M10+16-4e2ab919-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: C:\Users\hepin\.ivy2\local\org.scalameta\munit_native0.5.0-SNAPSHOT_3\1.0.0-M10+16-4e2ab919-SNAPSHOT\ivys\ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scalameta/munit_native0.5.0-SNAPSHOT_3/1.0.0-M10+16-4e2ab919-SNAPSHOT/munit_native0.5.0-SNAPSHOT_3-1.0.0-M10+16-4e2ab919-SNAPSHOT.pom
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/org/scalameta/munit_native0.5.0-SNAPSHOT_3/1.0.0-M10+16-4e2ab919-SNAPSHOT/munit_native0.5.0-SNAPSHOT_3-1.0.0-M10+16-4e2ab919-SNAPSHOT.pom
[error] Total time: 20 s, completed 2024年1月24日 22:23:48
```

@armanbilge Munit is not published.

`ThisBuild / resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots/"`

**Comment by natsukagami** [comment]
I plan to release 0.2 alongside SN 0.5.0 when the latter is available.

**Comment by barriem** [comment]
building the dependencies locally worked for me, thanks!  One issue I had was with the [nix flake](https://github.com/lampepfl/gears/blob/main/flake.nix#L20) when running `nix develop` - I'm not sure why, but the SBT override wasn't being picked up.

Explicitly setting the JDK as a dependency for the dev shell solved this for me - e.g:
```
 devShells.default = pkgs.mkShell {
          buildInputs = with pkgs; [
            jdk21
            # Scala deps
            (sbt.override { jre = jdk21; })
            ....
            etc
```

**Comment by natsukagami** [comment]
It's published ;)
